// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA012EPYkoPjwlplThlshjH4Wg6QkFpKkA',
    appId: '1:839325685238:web:924599b12ab478b785a3d7',
    messagingSenderId: '839325685238',
    projectId: 'myfirstapp-1f2a2',
    authDomain: 'myfirstapp-1f2a2.firebaseapp.com',
    storageBucket: 'myfirstapp-1f2a2.firebasestorage.app',
    measurementId: 'G-8DPP7Z9XSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMGnuJA5qhXHQC8KmeUmjyBk2uv3ZcWCg',
    appId: '1:839325685238:android:540446f65d905a2c85a3d7',
    messagingSenderId: '839325685238',
    projectId: 'myfirstapp-1f2a2',
    storageBucket: 'myfirstapp-1f2a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNQQ5wty3x0GS8yx3mryD9kBWCzDkCecM',
    appId: '1:839325685238:ios:5364703b65517aa485a3d7',
    messagingSenderId: '839325685238',
    projectId: 'myfirstapp-1f2a2',
    storageBucket: 'myfirstapp-1f2a2.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNQQ5wty3x0GS8yx3mryD9kBWCzDkCecM',
    appId: '1:839325685238:ios:5364703b65517aa485a3d7',
    messagingSenderId: '839325685238',
    projectId: 'myfirstapp-1f2a2',
    storageBucket: 'myfirstapp-1f2a2.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA012EPYkoPjwlplThlshjH4Wg6QkFpKkA',
    appId: '1:839325685238:web:783de9eee5a66e3485a3d7',
    messagingSenderId: '839325685238',
    projectId: 'myfirstapp-1f2a2',
    authDomain: 'myfirstapp-1f2a2.firebaseapp.com',
    storageBucket: 'myfirstapp-1f2a2.firebasestorage.app',
    measurementId: 'G-M1WZXGDB9H',
  );
}
